### ISSUE TITLE
Please add details about plugin to description

### ISSUE THREAD

**Issue by hznut** [webjars/webjars-maven-plugin#16]
Hi,

Questions regarding maven plugin: 
1. When we use the plugin with maven and do `mvn webjars:install foo`, will the dependency foo be downloaded right away and stored in some directory (like how bower downloads and stores in bower_components) ? 
2. If no then all that the maven command does is modify the `pom.xml` and add the `foo` dependency to it. But during which maven phase (`compile` / `package` / `install`) are the webjar dependencies downloaded by the plugin ?
3. If I want to create a webjar of my own maven based project how do I do it ? Is it necessary that the jar should have following structure like ? OR can I create my own directory structure ?
   
   ```
   META-INF/maven/com.my.company/foo/pom.xml
   META-INF/resources/webjars/foo/X.Y.Z/foo.js
   META-INF/resources/webjars/foo/X.Y.Z/foo.min.js
   META-INF/resources/webjars/foo/X.Y.Z/foo.css
   META-INF/resources/webjars/foo/X.Y.Z/foo.min.css
   ```
4. Does this plugin do transitive dependency resolution ?

**Comment by jamesward** [comment]
@mwanji Can you respond to this?

**Comment by mwanji** [comment]
The plugin is basically a small utility for Maven, so it leverages the way Maven works by just rewriting the POM. So the answers to questions 1, 2 and 4 are: it lets Maven handle it. 

Maven downloads dependencies to a central location. When packaging, dependencies may be bundled with the artifact (this is the case when creating a WAR, for example).

The plugin does not download the dependencies, it lets Maven download them and resolve transitive dependencies. I don't remember in which phase dependencies are resolved and downloaded, but it's before the compile phase.

Question 3: Documentation of how to create your own webjar is best handled on the main webjar project. The basic folder structure is based on the Servlet 3 specification. If you don't need your resources to be picked up by webjars-locator, they only need to be in META-INF/resources. Otherwise, put them in the same folder structure as every other webjar, which you can see by either opening a JAR file or in your IDE.

**Comment by hznut** [comment]
Thanks for the explanation. It helps.

**Comment by jamesward** [comment]
Thanks @mwanji!
